# Generated by Django 2.2 on 2019-05-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
